export enum KandidatutfallTyper {
  IKKE_PRESENTERT = 'IKKE_PRESENTERT',
  PRESENTERT = 'PRESENTERT',
  FATT_JOBBEN = 'FATT_JOBBEN',
}

export enum TilstandPåForespørsel {
  KAN_IKKE_OPPRETTE = 'KAN_IKKE_OPPRETTE',
  PROVER_VARSLING = 'PROVER_VARSLING',
  HAR_VARSLET = 'HAR_VARSLET',
  KAN_IKKE_VARSLE = 'KAN_IKKE_VARSLE',
  HAR_SVART = 'HAR_SVART',
  AVBRUTT = 'AVBRUTT',
}

export enum InternKandidatstatus {
  VURDERES = 'VURDERES',
  KONTAKTET = 'KONTAKTET',
  AKTUELL = 'AKTUELL',
  TIL_INTERVJU = 'TIL_INTERVJU',
  UAKTUELL = 'UAKTUELL',
  UINTERESSERT = 'UINTERESSERT',
}
