version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Oslo"
    versioning-strategy: "lockfile-only"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "pnpm"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      # Group patch updates
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      # Group NAV packages
      nav-packages:
        patterns:
          - "@navikt/*"
      # Group dev dependencies
      dev-dependencies:
        dependency-type: "development"
    ignore:
      # Ignore major version updates for Node.js LTS
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      # Add other packages to ignore if needed
      # - dependency-name: "example-package"