apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: toi
  name: rekrutteringsbistand-frontend
  namespace: toi
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  replicas:
    max: 1
    min: 1
  image: {{ image }}
  ingresses:
     - {{ NEXT_PUBLIC_BASE_URL }}
  port: 3000
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: {{ adGruppeModiaGenerellTilgang }}
          - id: {{ adGruppeModiaOppfolgg }}
          - id: {{ adGruppeRekrutteringsbistandArbeidsgiverrettet }}
          - id: {{ adGruppeRekrutteringsbistandJobbsokerrettet }}
          - id: {{ adGruppeRekrutteringsbistandUtvikler }}
        extra:
          - NAVident
    sidecar:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: rekrutteringsbistand-stilling-api
        - application: rekrutteringsbistand-stillingssok-proxy
        - application: rekrutteringsbistand-kandidatsok-api
        - application: rekrutteringsbistand-kandidatvarsel-api
        - application: toi-arbeidsgiver-notifikasjon
        - application: toi-synlighetsmotor
        - application: modiacontextholder
          namespace: personoversikt
        - application: pam-ontologi
          namespace: teampam
        - application: pam-search-api
          namespace: teampam
        - application: pam-geografi
          namespace: teampam
        - application: rekrutteringstreff-api
      external:
        - host: {{ statistikkApiHost }}
        - host: {{ foresporselOmDelingAvCvApiHost }}
        - host: {{ kandidatApiHost }}
        - host: {{ umamiSrc }}
        - host: {{ umamiUrl }}
        - host: {{ skyraSrc }}
        - host: {{ skyraSurvey }}
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: NEXT_PUBLIC_BASE_URL
      value: {{ NEXT_PUBLIC_BASE_URL }}
    - name: AD_GRUPPE_REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET
      value: {{ adGruppeRekrutteringsbistandArbeidsgiverrettet }}
    - name: AD_GRUPPE_REKRUTTERINGSBISTAND_JOBBSOKERRETTET
      value: {{ adGruppeRekrutteringsbistandJobbsokerrettet }}
    - name: AD_GRUPPE_REKRUTTERINGSBISTAND_UTVIKLER
      value: {{ adGruppeRekrutteringsbistandUtvikler }}
    - name: STATISTIKK_API
      value: {{ statistikkApiUrl}}
    - name: FORESPORSEL_OM_DELING_AV_CV_API
      value: {{ foresporselOmDelingAvCvApi }}
    - name: MODIA_CONTEXT_HOLDER_API
      value: http://modiacontextholder.personoversikt
    - name: STILLING_API
      value: http://rekrutteringsbistand-stilling-api
    - name: STILLINGSSOK_PROXY_URL
      value: http://rekrutteringsbistand-stillingssok-proxy
    - name: KANDIDATSOK_API
      value: http://rekrutteringsbistand-kandidatsok-api
    - name: KANDIDAT_API
      value: {{ kandidatApiUrl }}
    - name: PAM_ONTOLOGI_URL
      value: http://pam-ontologi.teampam
    - name: PAM_SEARCH_URL
      value: http://pam-search-api.teampam
    - name: PAM_GEOGRAFI_URL
      value: http://pam-geografi.teampam
    - name: KANDIDATVARSEL_API_URL
      value: http://rekrutteringsbistand-kandidatvarsel-api
    - name: ARBEIDSGIVER_NOTIFIKASJON_API
      value: http://toi-arbeidsgiver-notifikasjon
    - name: SYNLIGHETSMOTOR_API
      value: http://toi-synlighetsmotor
    - name: REKRUTTERINGSTREFF_API_URL
      value: http://rekrutteringstreff-api
    - name: NEXT_PUBLIC_UMAMI_ID
      value: {{ umamiId }}      
    - name: NEXT_PUBLIC_UMAMI_SRC
      value: {{ umamiSrc }}
    - name: NEXT_PUBLIC_UMAMI_URL
      value: {{ umamiUrl }}
    - name: NEXT_PUBLIC_DECORATOR_SRC
      value: {{ decoratorSrc }}