apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: toi
  name: rekrutteringsbistand-next
  namespace: toi
spec:
  ingresses:
    - https://rekrutteringsbistand-next.intern.dev.nav.no
  image: { { image } }
  port: 3000
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
