apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: toi
  name: rekrutteringsbistand-next
  namespace: toi
spec:
  replicas:
    max: 1
    min: 1
  image: {{ image }}
  ingresses:
    - https://rekrutteringsbistand-next.intern.dev.nav.no
  port: 3000
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: {{ adGruppeModiaGenerellTilgang }}
          - id: {{ adGruppeModiaOppfolging }}
          - id: {{ adGruppeRekrutteringsbistandArbeidsgiverrettet }}
          - id: {{ adGruppeRekrutteringsbistandJobbsokerrettet }}
          - id: {{ adGruppeRekrutteringsbistandUtvikler }}
        extra:
          - NAVident
    sidecar:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: modiacontextholder
          namespace: personoversikt
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: AD_GRUPPE_REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET
      value: {{ adGruppeRekrutteringsbistandArbeidsgiverrettet }}
    - name: AD_GRUPPE_REKRUTTERINGSBISTAND_JOBBSOKERRETTET
      value: {{ adGruppeRekrutteringsbistandJobbsokerrettet }}
    - name: AD_GRUPPE_REKRUTTERINGSBISTAND_UTVIKLER
      value: {{ adGruppeRekrutteringsbistandUtvikler }}
    - name: STATISTIKK_API_URL
      value: http://rekrutteringsbistand-statistikk-api
    - name: MODIA_CONTEXT_HOLDER_API
      value: http://modiacontextholder.personoversikt
