export enum Roller {
  AD_GRUPPE_MODIA_GENERELL_TILGANG = 'AD_GRUPPE_MODIA_GENERELL_TILGANG',
  AD_GRUPPE_MODIA_OPPFOLGING = 'AD_GRUPPE_MODIA_OPPFOLGING',
  AD_GRUPPE_REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET = 'AD_GRUPPE_REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET',
  AD_GRUPPE_REKRUTTERINGSBISTAND_JOBBSOKERRETTET = 'AD_GRUPPE_REKRUTTERINGSBISTAND_JOBBSOKERRETTET',
  AD_GRUPPE_REKRUTTERINGSBISTAND_UTVIKLER = 'AD_GRUPPE_REKRUTTERINGSBISTAND_UTVIKLER',
}

const {
  AD_GRUPPE_MODIA_GENERELL_TILGANG,
  AD_GRUPPE_MODIA_OPPFOLGING,
  AD_GRUPPE_REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET,
  AD_GRUPPE_REKRUTTERINGSBISTAND_JOBBSOKERRETTET,
  AD_GRUPPE_REKRUTTERINGSBISTAND_UTVIKLER,
} = process.env;

export const navnForRolleId = (rolleId: string): string | null => {
  switch (rolleId) {
    case AD_GRUPPE_MODIA_GENERELL_TILGANG:
      return Roller.AD_GRUPPE_MODIA_GENERELL_TILGANG;
    case AD_GRUPPE_MODIA_OPPFOLGING:
      return Roller.AD_GRUPPE_MODIA_OPPFOLGING;
    case AD_GRUPPE_REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET:
      return Roller.AD_GRUPPE_REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET;
    case AD_GRUPPE_REKRUTTERINGSBISTAND_JOBBSOKERRETTET:
      return Roller.AD_GRUPPE_REKRUTTERINGSBISTAND_JOBBSOKERRETTET;
    case AD_GRUPPE_REKRUTTERINGSBISTAND_UTVIKLER:
      return Roller.AD_GRUPPE_REKRUTTERINGSBISTAND_UTVIKLER;
    default:
      return null;
  }
};
