import { SamletKvalifikasjonDTO } from './useSamledeKvalifikasjoner';

export const samledeKvalifikasjonerMock: SamletKvalifikasjonDTO[] = [
  {
    konseptId: 175819,
    styrk08: '5120',
    styrk08Label: 'Kokker',
    esco: '',
    escoLabel: '',
    label: 'Kokk',
    undertype: '',
    kategori: 'YRKESTITTEL',
  },
  {
    konseptId: 240122,
    styrk08: '5120',
    styrk08Label: 'Kokker',
    esco: '',
    escoLabel: '',
    label: 'Kokkelærling',
    undertype: '',
    kategori: 'YRKESTITTEL',
  },
  {
    konseptId: 91501,
    styrk08: '',
    styrk08Label: '',
    esco: '',
    escoLabel: '',
    label: 'Førerkort klasse B',
    undertype: '',
    kategori: 'FORERKORT',
  },
  {
    konseptId: 50121,
    styrk08: '',
    styrk08Label: '',
    esco: '',
    escoLabel: '',
    label: 'Matlaging',
    undertype: '',
    kategori: 'KOMPETANSE',
  },
  {
    konseptId: 80201,
    styrk08: '',
    styrk08Label: '',
    esco: '',
    escoLabel: '',
    label: 'Fagbrev som kokk',
    undertype: '',
    kategori: 'FAGDOKUMENTASJON',
  },
  {
    konseptId: 50988,
    styrk08: '',
    styrk08Label: '',
    esco: '',
    escoLabel: '',
    label: 'Servering',
    undertype: '',
    kategori: 'KOMPETANSE',
  },
  {
    konseptId: 50989,
    styrk08: '',
    styrk08Label: '',
    esco: '',
    escoLabel: '',
    label: 'Hygiene',
    undertype: '',
    kategori: 'KOMPETANSE',
  },
];
