import { z } from 'zod';

export const stillingSchema = z.object({
  stillingsinfo: z.object({
    stillingsid: z.string(),
    stillingsinfoid: z.string(),
    eierNavident: z.null(),
    eierNavn: z.null(),
    stillingskategori: z.string(),
  }),
  stilling: z.object({
    id: z.number(),
    uuid: z.string(),
    created: z.string(),
    createdBy: z.string(),
    updated: z.string(),
    updatedBy: z.string(),
    title: z.string(),
    status: z.string(),
    administration: z.object({
      id: z.number(),
      status: z.string(),
      comments: z.null(),
      reportee: z.string(),
      remarks: z.array(z.unknown()),
      navIdent: z.string(),
    }),
    mediaList: z.array(z.unknown()),
    contactList: z.array(z.unknown()),
    privacy: z.string(),
    source: z.string(),
    medium: z.string(),
    reference: z.string(),
    published: z.string(),
    expires: z.string(),
    employer: z.object({
      id: z.number(),
      uuid: z.string(),
      created: z.string(),
      createdBy: z.string(),
      updated: z.string(),
      updatedBy: z.string(),
      mediaList: z.array(z.unknown()),
      contactList: z.array(z.unknown()),
      location: z.object({
        address: z.string(),
        postalCode: z.string(),
        county: z.null(),
        municipal: z.null(),
        municipalCode: z.null(),
        city: z.string(),
        country: z.string(),
        latitude: z.null(),
        longitude: z.null(),
      }),
      locationList: z.array(
        z.object({
          address: z.string(),
          postalCode: z.string(),
          county: z.null(),
          municipal: z.null(),
          municipalCode: z.null(),
          city: z.string(),
          country: z.string(),
          latitude: z.null(),
          longitude: z.null(),
        }),
      ),
      properties: z.object({ nace2: z.string() }),
      name: z.string(),
      orgnr: z.string(),
      status: z.string(),
      parentOrgnr: z.string(),
      publicName: z.string(),
      deactivated: z.null(),
      orgform: z.string(),
      employees: z.number(),
    }),
    location: z.null(),
    locationList: z.array(z.unknown()),
    categoryList: z.array(z.unknown()),
    properties: z.object({}),
    publishedByAdmin: z.null(),
    businessName: z.string(),
    firstPublished: z.boolean(),
    deactivatedByExpiry: z.boolean(),
    activationOnPublishingDate: z.boolean(),
  }),
});
