import { z } from 'zod';

export const stillingSchema = z.object({
  stillingsinfo: z.object({
    stillingsid: z.string(),
    stillingsinfoid: z.string(),
    eierNavident: z.null(),
    eierNavn: z.null(),
    stillingskategori: z.string(),
  }),
  stilling: z.object({
    id: z.number(),
    uuid: z.string(),
    created: z.string(),
    createdBy: z.string(),
    updated: z.string(),
    updatedBy: z.string(),
    title: z.string(),
    status: z.string(),
    administration: z.object({
      id: z.number(),
      status: z.string(),
      comments: z.null(),
      reportee: z.string(),
      remarks: z.array(z.unknown()),
      navIdent: z.string(),
    }),
    mediaList: z.array(z.unknown()),
    contactList: z.array(
      z.object({
        name: z.string(),
        email: z.string(),
        phone: z.null(),
        role: z.null(),
        title: z.string(),
      }),
    ),
    privacy: z.string(),
    source: z.string(),
    medium: z.string(),
    reference: z.string(),
    published: z.string(),
    expires: z.string(),
    employer: z.object({
      id: z.number(),
      uuid: z.string(),
      created: z.string(),
      createdBy: z.string(),
      updated: z.string(),
      updatedBy: z.string(),
      mediaList: z.array(z.unknown()),
      contactList: z.array(z.unknown()),
      location: z.object({
        address: z.string(),
        postalCode: z.string(),
        county: z.null(),
        municipal: z.null(),
        municipalCode: z.null(),
        city: z.string(),
        country: z.string(),
        latitude: z.null(),
        longitude: z.null(),
      }),
      locationList: z.array(
        z.object({
          address: z.string(),
          postalCode: z.string(),
          county: z.null(),
          municipal: z.null(),
          municipalCode: z.null(),
          city: z.string(),
          country: z.string(),
          latitude: z.null(),
          longitude: z.null(),
        }),
      ),
      properties: z.object({ nace2: z.string() }),
      name: z.string(),
      orgnr: z.string(),
      status: z.string(),
      parentOrgnr: z.string(),
      publicName: z.string(),
      deactivated: z.null(),
      orgform: z.string(),
      employees: z.number(),
    }),
    location: z.object({
      address: z.null(),
      postalCode: z.null(),
      county: z.string(),
      municipal: z.string(),
      municipalCode: z.string(),
      city: z.null(),
      country: z.string(),
      latitude: z.null(),
      longitude: z.null(),
    }),
    locationList: z.array(
      z.object({
        address: z.null(),
        postalCode: z.null(),
        county: z.string(),
        municipal: z.string(),
        municipalCode: z.string(),
        city: z.null(),
        country: z.string(),
        latitude: z.null(),
        longitude: z.null(),
      }),
    ),
    categoryList: z.array(
      z.object({
        id: z.number(),
        code: z.string(),
        categoryType: z.string(),
        name: z.string(),
        description: z.null(),
        parentId: z.null(),
      }),
    ),
    properties: z.object({
      extent: z.string(),
      workhours: z.string(),
      workday: z.string(),
      applicationdue: z.string(),
      jobtitle: z.string(),
      positioncount: z.string(),
      engagementtype: z.string(),
      classification_styrk08_score: z.string(),
      starttime: z.string(),
      adtext: z.string(),
      classification_styrk08_code: z.string(),
      tags: z.string(),
      searchtags: z.string(),
      classification_esco_code: z.string(),
      classification_input_source: z.string(),
      sector: z.string(),
    }),
    publishedByAdmin: z.string(),
    businessName: z.string(),
    firstPublished: z.boolean(),
    deactivatedByExpiry: z.boolean(),
    activationOnPublishingDate: z.boolean(),
  }),
});
