apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: rekrutteringsbistand-frontend
    namespace: toi
    labels:
        team: toi
spec:
    groups:
        - name: rekrutteringsbistand-frontend
          rules:
              - alert: rekrutteringsbistand-frontend
                expr: kube_deployment_status_replicas_available{deployment="rekrutteringsbistand-frontend"} == 0
                for: 1s
                annotations:
                    summary: Appen er nede
                    action: "https://logs.adeo.no/app/r/s/ywDkg"
                labels:
                    namespace: toi
                    severity: critical

              - alert: rekrutteringsbistand-frontend
                expr: sum(increase(log_messages_errors{app="rekrutteringsbistand-frontend", level="Error"}[10m])) > 0
                for: 1s
                annotations:
                    summary: Appen har logget en error
                    action: "https://logs.adeo.no/app/r/s/ywDkg"
                labels:
                    namespace: toi
                    severity: critical

              - alert: rekrutteringsbistand-frontend
                expr: sum(increase(log_messages_errors{app="rekrutteringsbistand-frontend", level="Warning"}[10m])) > 3
                for: 1s
                annotations:
                    summary: Økning i warnings
                    action: "https://logs.adeo.no/app/r/s/ywDkg"
                labels:
                    namespace: toi
                    severity: warning
