apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: toi
  name: rekrutteringsbistand-frontend
  namespace: toi
spec:
  replicas:
    max: 1
    min: 1
  image: {{ image }}
  ingresses: &base_url
    - https://rekrutteringsbistand-frontend.intern.dev.nav.no
  port: 3000
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: {{ adGruppeModiaGenerellTilgang }}
          - id: {{ adGruppeModiaOppfolging }}
          - id: {{ adGruppeRekrutteringsbistandArbeidsgiverrettet }}
          - id: {{ adGruppeRekrutteringsbistandJobbsokerrettet }}
          - id: {{ adGruppeRekrutteringsbistandUtvikler }}
        extra:
          - NAVident
    sidecar:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: rekrutteringsbistand-stilling-api
        - application: rekrutteringsbistand-stillingssok-proxy
        - application: rekrutteringsbistand-kandidatsok-api
        - application: modiacontextholder
          namespace: personoversikt
      external:
        - host: {{ statistikkApiHost }}
        - host: {{ foresporselOmDelingAvCvApiHost }}
        - host: {{ kandidatApiHost }}
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: NEXT_PUBLIC_BASE_URL
      value: *base_url[0]
    - name: AD_GRUPPE_REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET
      value: {{ adGruppeRekrutteringsbistandArbeidsgiverrettet }}
    - name: AD_GRUPPE_REKRUTTERINGSBISTAND_JOBBSOKERRETTET
      value: {{ adGruppeRekrutteringsbistandJobbsokerrettet }}
    - name: AD_GRUPPE_REKRUTTERINGSBISTAND_UTVIKLER
      value: {{ adGruppeRekrutteringsbistandUtvikler }}
    - name: STATISTIKK_API
      value: {{ statistikkApiUrl}}
    - name: FORESPORSEL_OM_DELING_AV_CV_API
      value: {{ foresporselOmDelingAvCvApi }}
    - name: MODIA_CONTEXT_HOLDER_API
      value: http://modiacontextholder.personoversikt
    - name: STILLING_API
      value: http://rekrutteringsbistand-stilling-api
    - name: STILLINGSSOK_PROXY_URL
      value: http://rekrutteringsbistand-stillingssok-proxy
    - name: KANDIDATSOK_API
      value: http://rekrutteringsbistand-kandidatsok-api
    - name: KANDIDAT_API
      value: {{ kandidatApiUrl }}