'use client';

import useSWRImmutable from 'swr/immutable';
import { z } from 'zod';
import { PamOntologiAPI } from '../../api-routes';
import { getAPIwithSchema } from '../../fetcher';

const pamEndepunkt = (søkeord: string) =>
  PamOntologiAPI.internUrl + `/stillingsTittel?q=${søkeord}`;

const stillingsTittelSchema = z.object({
  konseptId: z.number(),
  styrk08: z.string(),
  esco: z.string(),
  escoLabel: z.string(),
  label: z.string(),
  undertype: z.string(),
});

export const stillingsTittelTreffSchema = z.array(stillingsTittelSchema);

export type stillingsTittelDTO = z.infer<typeof stillingsTittelSchema>;

export const useStillingsTittel = (søkeOrd?: string) =>
  useSWRImmutable(
    søkeOrd ? pamEndepunkt(søkeOrd) : null,
    getAPIwithSchema(stillingsTittelTreffSchema, {
      'Nav-CallId': 'rekrutteringsbistand-frontend',
    }),
  );

export const stillingsTittelMirage = (server: any) =>
  server.get(PamOntologiAPI.internUrl + `/stillingsTittel`, () => {
    return [
      {
        konseptId: 175819,
        styrk08: '3411',
        esco: '',
        escoLabel: '',
        label: 'Testamentåpningsrepresentant',
        undertype: '',
      },
      {
        konseptId: 216011,
        styrk08: '2519',
        esco: 'http://data.europa.eu/esco/occupation/106f79e4-6264-45f1-9e7a-297435cd684b',
        escoLabel: 'programvaretester',
        label: 'Test automatiseringsingeniør',
        undertype: '',
      },
      {
        konseptId: 109237,
        styrk08: '7543',
        esco: 'http://data.europa.eu/esco/isco/C7543',
        escoLabel: 'Produkttestere (ikke matprodukter)',
        label: 'Tester',
        undertype: '',
      },
      {
        konseptId: 327556,
        styrk08: '3112',
        esco: 'http://data.europa.eu/esco/occupation/adf9257e-78cb-467d-b259-59ed65bd7aed',
        escoLabel: 'branntekniker',
        label: 'Tester af brannsikkerhet, materialtester',
        undertype: '',
      },
      {
        konseptId: 2486745,
        styrk08: '2519',
        esco: 'http://data.europa.eu/esco/occupation/50af07f0-7a75-424e-a66d-5a9deea10f4c',
        escoLabel: 'IKT-tilgjengelighetstester',
        label: 'Tester av IKT-tilgjengelighet',
        undertype: '',
      },
      {
        konseptId: 164706,
        styrk08: '7515',
        esco: '',
        escoLabel: '',
        label: 'Tester av ølkvalitet',
        undertype: '',
      },
      {
        konseptId: 327679,
        styrk08: '3115',
        esco: 'http://data.europa.eu/esco/occupation/80a648c5-ecb7-40e6-a4d4-7680291ffa74',
        escoLabel: 'motorkontrollør, rullende materiell',
        label: 'Tester for lokomotivdrift',
        undertype: '',
      },
      {
        konseptId: 97173,
        styrk08: '2149',
        esco: 'http://data.europa.eu/esco/occupation/c8fa93eb-7c2c-42c3-b135-c2e825a6615e',
        escoLabel: 'testingeniør',
        label: 'Testingeniør',
        undertype: '',
      },
      {
        konseptId: 241051,
        styrk08: '2152',
        esco: 'http://data.europa.eu/esco/occupation/2026adb2-62d7-4b92-9ccb-105abdebe37d',
        escoLabel: 'ingeniør, elektromagnetisme',
        label: 'Testingeniør electro magnetic compatibility (EMC)',
        undertype: '',
      },
      {
        konseptId: 113983,
        styrk08: '3114',
        esco: 'http://data.europa.eu/esco/isco/C2153',
        escoLabel: 'Sivilingeniører (telekommunikasjon)',
        label: 'Testingeniør elektronikk og telekommunikasjon',
        undertype: '',
      },
      {
        konseptId: 2481251,
        styrk08: '1330',
        esco: 'http://data.europa.eu/esco/occupation/52d5edc9-7902-4cd3-8b06-6bd77c98d440',
        escoLabel: 'IKT-systemtester',
        label: 'Testingeniør IT',
        undertype: '',
      },
      {
        konseptId: 114013,
        styrk08: '3115',
        esco: '',
        escoLabel: '',
        label: 'Testingeniør (Maskiner)',
        undertype: '',
      },
      {
        konseptId: 391597,
        styrk08: '3117',
        esco: 'http://data.europa.eu/esco/isco/C2149',
        escoLabel: 'Andre sivilingeniører (unntatt elektroteknologi)',
        label: 'Testingeniør piping',
        undertype: '',
      },
      {
        konseptId: 69290,
        styrk08: '2519',
        esco: 'http://data.europa.eu/esco/occupation/106f79e4-6264-45f1-9e7a-297435cd684b',
        escoLabel: 'programvaretester',
        label: 'Testingeniør (Software)',
        undertype: '',
      },
      {
        konseptId: 109237,
        styrk08: '7543',
        esco: 'http://data.europa.eu/esco/isco/C7543',
        escoLabel: 'Produkttestere (ikke matprodukter)',
        label: 'Testleder',
        undertype: '',
      },
      {
        konseptId: 366439,
        styrk08: '2146',
        esco: 'http://data.europa.eu/esco/occupation/7569f423-2c37-49aa-947e-41acb66ec909',
        escoLabel: 'petroleumsingeniør',
        label: 'Testplanlegger (olje og gass)',
        undertype: '',
      },
      {
        konseptId: 316682,
        styrk08: '3114',
        esco: 'http://data.europa.eu/esco/isco/C3114',
        escoLabel: 'Elektronikkingeniører',
        label: 'Testtekniker elektronikk',
        undertype: '',
      },
      {
        konseptId: 107115,
        styrk08: '3259',
        esco: 'http://data.europa.eu/esco/occupation/16e65196-3449-4c88-b379-0aa98f43db2b',
        escoLabel: 'anestesitekniker',
        label: 'Anestesiassistent',
        undertype: '',
      },
      {
        konseptId: 21479,
        styrk08: '2212',
        esco: 'http://data.europa.eu/esco/occupation/9b889f07-c39c-464d-b9d9-b2daa650f9ac',
        escoLabel: 'spesiallege',
        label: 'Anestesilege',
        undertype: '',
      },
      {
        konseptId: 157685,
        styrk08: '2212',
        esco: 'http://data.europa.eu/esco/occupation/9b889f07-c39c-464d-b9d9-b2daa650f9ac',
        escoLabel: 'spesiallege',
        label: 'Anestesioverlege',
        undertype: '',
      },
      {
        konseptId: 107056,
        styrk08: '2221',
        esco: 'http://data.europa.eu/esco/occupation/18e14e61-495b-44cc-a7c6-df4c625934ba',
        escoLabel: 'spesialsykepleier',
        label: 'Anestesisykepleier',
        undertype: '',
      },
      {
        konseptId: 1105828,
        styrk08: '2519',
        esco: 'http://data.europa.eu/esco/occupation/0ab5c12c-c1c1-4772-8345-aa287d0e391d',
        escoLabel: 'IKT-testanalytiker',
        label: 'API Tester',
        undertype: '',
      },
      {
        konseptId: 216011,
        styrk08: '2519',
        esco: 'http://data.europa.eu/esco/occupation/106f79e4-6264-45f1-9e7a-297435cd684b',
        escoLabel: 'programvaretester',
        label: 'Automatiseringsingeniør kontroll og testing',
        undertype: '',
      },
      {
        konseptId: 378698,
        styrk08: '5222',
        esco: 'http://data.europa.eu/esco/occupation/974494ee-5f32-4eec-9950-9d431e902dc1',
        escoLabel: 'spesialisert selger, kjøtt og kjøttprodukter',
        label: 'Avdelingsleder Kjøtt & Delikatesse',
        undertype: '',
      },
      {
        konseptId: 100578,
        styrk08: '7125',
        esco: 'http://data.europa.eu/esco/occupation/211716b7-2857-40c8-a078-da983c78c70a',
        escoLabel: 'bilrutemontør',
        label: 'Bilglass-/ruteskifter',
        undertype: '',
      },
      {
        konseptId: 312135,
        styrk08: '8342',
        esco: 'http://data.europa.eu/esco/occupation/1bcc6461-4cc2-4732-a6d0-901687046443',
        escoLabel: 'snømåker',
        label: 'Brøytesjåfør',
        undertype: '',
      },
      {
        konseptId: 1627031,
        styrk08: '3259',
        esco: 'http://data.europa.eu/esco/occupation/c56bb750-db0b-487b-89f4-82dee6dcab09',
        escoLabel: 'covid-tester',
        label: 'Covid-tester',
        undertype: '',
      },
      {
        konseptId: 2488061,
        styrk08: '3114',
        esco: '',
        escoLabel: '',
        label: 'Datatekniker, maskinvaretester',
        undertype: '',
      },
      {
        konseptId: 2612009,
        styrk08: '2341',
        esco: '',
        escoLabel: '',
        label: 'Fagpedagog (Montessoriskole)',
        undertype: '',
      },
      {
        konseptId: 97680,
        styrk08: '7543',
        esco: 'http://data.europa.eu/esco/occupation/82d75f3b-644a-4582-ad6b-a2a1833e44cb',
        escoLabel: 'spesialist innen ikke-destruktiv testing',
        label: 'Fagperson innen ikke-destruktiv testing',
        undertype: '',
      },
      {
        konseptId: 35442,
        styrk08: '1324',
        esco: '',
        escoLabel: '',
        label: 'Flåtesjef (kjøretøypark)',
        undertype: '',
      },
      {
        konseptId: 212842,
        styrk08: '3115',
        esco: 'http://data.europa.eu/esco/occupation/b343dd0c-8a83-4e13-a79c-0ac52f526c64',
        escoLabel: 'flymotortester',
        label: 'Flymotortester',
        undertype: '',
      },
      {
        konseptId: 156451,
        styrk08: '2152',
        esco: 'http://data.europa.eu/esco/occupation/608edf30-fe37-4ae5-bdd1-2d3a8fd347bd',
        escoLabel: 'ingeniør, testflyvning',
        label: 'Flytestingeniør',
        undertype: '',
      },
      {
        konseptId: 129975,
        styrk08: '3343',
        esco: 'http://data.europa.eu/esco/occupation/8cce40c1-4479-47e7-b5fc-c976631d919f',
        escoLabel: 'administrasjonsassistent',
        label: 'Førstesekretær (direksjonsadministrasjon)',
        undertype: '',
      },
      {
        konseptId: 236805,
        styrk08: '3353',
        esco: 'http://data.europa.eu/esco/occupation/2c83f279-a1d1-4c9f-a6aa-5e5ee1850e46',
        escoLabel: 'trygdeinspektør',
        label: 'Førstesekretær i Trygdeetaten',
        undertype: '',
      },
      {
        konseptId: 69369,
        styrk08: '3343',
        esco: 'http://data.europa.eu/esco/occupation/044d78cc-f62f-4532-83a5-8e04f2889652',
        escoLabel: 'administrativ assistent',
        label: 'Førstesekretær (offentlig administrasjon)',
        undertype: '',
      },
      {
        konseptId: 105508,
        styrk08: '3343',
        esco: 'http://data.europa.eu/esco/occupation/2a04a1df-a3b9-403e-a245-e7f93fdddd44',
        escoLabel: 'administrasjonssekretær',
        label: 'Førstesekretær (privat viksomhet)',
        undertype: '',
      },
      {
        konseptId: 1234562,
        styrk08: '2611',
        esco: 'http://data.europa.eu/esco/occupation/acf462a3-9c34-46cb-952a-c612c38299f4',
        escoLabel: 'anklager',
        label: 'Førstestatsadvokat (embetsleder)',
        undertype: '',
      },
      {
        konseptId: 364596,
        styrk08: '3211',
        esco: 'http://data.europa.eu/esco/isco/C3211',
        escoLabel: 'Radiografer mv.',
        label: 'Førstestråleterapeut',
        undertype: '',
      },
      {
        konseptId: 102976,
        styrk08: '3152',
        esco: 'http://data.europa.eu/esco/occupation/e3df1f82-3df9-41e5-8487-635e184653d1',
        escoLabel: 'dekksoffiser',
        label: 'Førstestyrmann',
        undertype: '',
      },
      {
        konseptId: 361487,
        styrk08: '1311',
        esco: 'http://data.europa.eu/esco/isco/C1311',
        escoLabel: 'Ledere i skogbruk',
        label: 'Fylkesjordskiftesjef',
        undertype: '',
      },
      {
        konseptId: 364671,
        styrk08: '1349',
        esco: 'http://data.europa.eu/esco/isco/C1349',
        escoLabel: 'Andre ledere av produksjon og tjenesteyting',
        label: 'Fylkesskattesjef',
        undertype: '',
      },
      {
        konseptId: 217188,
        styrk08: '9510',
        esco: 'http://data.europa.eu/esco/isco/C521',
        escoLabel: 'Torg og markedsselgere',
        label: 'Gateselger',
        undertype: '',
      },
      {
        konseptId: 66609,
        styrk08: '5212',
        esco: 'http://data.europa.eu/esco/isco/C5212',
        escoLabel: 'Gateselgere',
        label: 'Gateselger mat',
        undertype: '',
      },
      {
        konseptId: 1628790,
        styrk08: '3259',
        esco: 'http://data.europa.eu/esco/isco/C3259',
        escoLabel: 'Andre helseyrker',
        label: 'Helsepersonell til testteam og smittesporing',
        undertype: '',
      },
      {
        konseptId: 90832,
        styrk08: '9214',
        esco: 'http://data.europa.eu/esco/isco/C9214',
        escoLabel: 'Hjelpearbeidere i gartneri mv.',
        label: 'Hjelpearbeider ved planteskole',
        undertype: '',
      },
      {
        konseptId: 1633157,
        styrk08: '2519',
        esco: 'http://data.europa.eu/esco/occupation/5f50290d-f520-4a69-85c7-1390d2a4a8b6',
        escoLabel: 'IKT-brukbarhetstester',
        label: 'IKT-brukbarhetstester',
        undertype: '',
      },
      {
        konseptId: 97713,
        styrk08: '2149',
        esco: 'http://data.europa.eu/esco/occupation/c8fa93eb-7c2c-42c3-b135-c2e825a6615e',
        escoLabel: 'testingeniør',
        label: 'Ingeniør for testing og prøving',
        undertype: '',
      },
      {
        konseptId: 386370,
        styrk08: '2511',
        esco: 'http://data.europa.eu/esco/occupation/bd9d395a-d587-45c6-8d72-ceef226df9e1',
        escoLabel: 'IKT-systemintegrasjonskonsulent',
        label: 'Integration and Test Automation Engineer',
        undertype: '',
      },
      {
        konseptId: 1200806,
        styrk08: '2529',
        esco: '',
        escoLabel: '',
        label: 'IT Penetration Tester',
        undertype: '',
      },
    ];
  });
