name: Dependabot PNPM Support

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - '**/package.json'
      - 'pnpm-lock.yaml'

jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Update lockfile
        run: pnpm install --lockfile-only
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update pnpm lockfile'
          file_pattern: pnpm-lock.yaml