name: Deploy
on:
  workflow_run:
    workflows: ['Push']
    types:
      - completed

jobs:
  deploy:
    name: Deploy to NAIS
    runs-on: ubuntu-latest
    needs: push
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to NAIS
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml
          VAR: image=${{ needs.push.outputs.image }}
