name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        registry-url: "https://npm.pkg.github.com"
    - name: Install dependencies
      env:
        NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      run: npm ci && npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start Node application
      run: npm run dev &
    - name: Test application
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: !success()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' # Only run this step on the main branch
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages  # the target branch
          keep_files: true 