name: Push
on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed

jobs:
  push:
    name: Push Docker Image to GAR
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Push Docker Image to GAR
        uses: nais/docker-build-push@v0
        id: docker-push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        with:
          team: toi
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          build_secrets: 'NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}'
          image: ${{ needs.build.outputs.image }}
