name: Trivy security scan
on:
  schedule:
    - cron: '40 5 * * 1'
  push:
    branches:
      - fiks-ukentlig-trivyscan

jobs:
  call-trivy-security-scan:
    uses: navikt/toi-github-actions-workflows/.github/workflows/trivy-security-scan.yaml@fiks-ukentlig-trivyscan
    permissions:
      id-token: write
      security-events: write
    secrets: inherit
