name: Bygg og Deploy Rekrutteringsbistand-frontend
on:
  push:
  workflow_dispatch:
    inputs:
      kjor-chainguard-sjekk:
        description: Kjør Chainguard-sjekken før bygg og deploy
        required: false
        type: boolean
        default: false
  schedule:
    - cron: '0 6 * * *'

jobs:
  build-and-deploy:
    name: Next
    uses: navikt/toi-frontend-workflows/.github/workflows/build-and-deploy-nextjs.yaml@v3
    with:
      chainguard-image: europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/node:24
      chainguard-digest-variabel: CHAINGUARD_NODE_24_DIGEST
      chainguard-sjekk: ${{ inputs.kjor-chainguard-sjekk == true }}
      playwright-command: 'pnpm run test'
      playwright-shards: 4
      playwright-snapshots: true
      playwright-github-report: true
      a11y-command: 'pnpm a11y'
      dev-vars-path: '.nais/dev-gcp.json'
      dev2-vars-path: '.nais/dev2-gcp.json'
      prod-vars-path: '.nais/prod-gcp.json'
      deploy-dev-branch: 'brukerinstillinger-api'
      deploy-dev2-branch: 'kandidatsok-orgenhet'
    secrets: inherit
    permissions:
      actions: write
      contents: write
      id-token: write
      security-events: write
      pages: write
