name: Bygg og Deploy Rekrutteringsbistand-frontend
on:
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: 🤖
    uses: navikt/toi-frontend-workflows/.github/workflows/build-and-deploy-nextjs.yaml@v3.2
    with:
      baseimage: europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/node:24
      playwright-command: 'pnpm run test'
      playwright-shards: 4
      playwright-snapshots: true
      playwright-github-report: true
      a11y-command: 'pnpm a11y'
      dev-vars-path: '.nais/dev-gcp.json'
      dev2-vars-path: '.nais/dev2-gcp.json'
      prod-vars-path: '.nais/prod-gcp.json'
      deploy-dev-branch: 'gunn'
      deploy-dev2-branch: 'dev2'
    secrets: inherit
    permissions:
      actions: write
      contents: write
      id-token: write
      security-events: write
      pages: write
